name: ${project.name}
version: ${project.version}
build: ${buildNumber}
main: ${main.class}
author: ${author}
api-version: 1.16

softdepend:
  - PlaceholderAPI
  - Vault
  - EcoBits


libraries:
  - com.google.code.gson:gson:2.8.9
  - org.apache.commons:commons-lang3:3.14.0

permissions:
  markets.command.stats:
    description: Allows access to the /markets stats command
    default: false
  markets.viewstats:
    description: Allows viewing market statistics GUI
    default: false